plugins: rubocop-rails

inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  TargetRailsVersion: 8.0
  SuggestExtensions: false
  Exclude:
    - db/**/*

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120
